In [3]:
import numpy as np

In [10]:
s = np.array(5)
print(s)

5


In [11]:
s.shape

()

In [12]:
x = s + 3

In [13]:
x

8

In [14]:
v = np.array([1,2,3])

In [15]:
x = v[1]

In [16]:
x

2

In [17]:
v[1:]

array([2, 3])

In [19]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
m.shape

(3, 3)

In [21]:
m[1][1]

5

In [22]:
m[0][0]

1

In [23]:
v = np.array([1,2,3,4])

In [24]:
v.shape

(4,)

In [25]:
x = v.reshape(1,4)

In [26]:
x

array([[1, 2, 3, 4]])

In [27]:
x.shape

(1, 4)

In [28]:
x = v.reshape(4,1)

x

In [30]:
x = v.reshape(2,2)

In [31]:
x

array([[1, 2],
       [3, 4]])

In [34]:
x = v[None, :]

In [35]:
x

array([[1, 2, 3, 4]])

In [36]:
x.shape

(1, 4)

In [37]:
x = v[:, None]

In [38]:
x

array([[1],
       [2],
       [3],
       [4]])

## element wise operations

In [39]:
values = [1,2,3,4,5]

In [41]:
values = np.array(values) + 5

In [42]:
values

array([ 6,  7,  8,  9, 10])

In [44]:
x = np.multiply(values, 5)

In [45]:
x

array([30, 35, 40, 45, 50])

In [46]:
x *= 0

In [47]:
x

array([0, 0, 0, 0, 0])

In [48]:
a = np.array([[1,3],[5,7]])

In [49]:
a

array([[1, 3],
       [5, 7]])

In [50]:
b = np.array([[2,4],[6,8]])

In [51]:
a + b

array([[ 3,  7],
       [11, 15]])

In [52]:
m = np.array([[1,2,3],[4,5,6]])

In [53]:
n = m * 0.25
n

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ]])

In [54]:
m * n

array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

In [56]:
a = np.array([[1,2,3,4],[5,6,7,8]])

In [57]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [58]:
c = np.matmul(a,b)

In [59]:
c

array([[ 70,  80,  90],
       [158, 184, 210]])

In [60]:
np.dot(a,b)

array([[ 70,  80,  90],
       [158, 184, 210]])

In [61]:
a.dot(b)

array([[ 70,  80,  90],
       [158, 184, 210]])

In [62]:
b.dot(a)

ValueError: shapes (4,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)

In [64]:
m = np.array([[1,2,3,4],[5,6,7,8],[9, 10, 11, 12]])

In [65]:
m.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [66]:
inputs = np.array([[-0.27,0.45, 0.64, 0.31]])

In [67]:
weights = np.array([[0.02, 0.001, -0.03, 0.036], [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])

In [68]:
np.matmul(inputs,weights.T)

array([[-0.01299,  0.00664,  0.13494]])

In [69]:
np.matmul(weights, inputs.T)

array([[-0.01299],
       [ 0.00664],
       [ 0.13494]])

In [71]:
inputs.min()

-0.27

In [74]:
inputs.shape[1]

4

In [76]:
inputs.mean()

0.28250000000000003